---

- name: Add OpenJDK Java PPA repo
  apt_repository:
    repo: "{{ repourl_openjdk_java | default('ppa:openjdk-r/ppa') }}"

- name: Update APT cache
  apt: update_cache=true

- name: Install OpenJDK Java
  apt: name=openjdk-8-jdk state=latest

- name: Create ZooKeeper group
  group: name=zookeeper state=present

- name: Create ZooKeeper user
  user: name=zookeeper shell=/bin/bash home=/opt/zookeeper createhome=no group=zookeeper

- name: Download ZooKeeper
  get_url: "url={{ zookeeper_url }} dest=/tmp/{{ zookeeper_file }}"

- name: Extract ZooKeeper
  unarchive: "src=/tmp/{{ zookeeper_file }} dest=/opt remote_src=True"

- name: Create ZooKeeper "zookeeper" symlink
  file: "src=/opt/{{ zookeeper_name }} dest=/opt/zookeeper state=link"

- name: Create ZooKeeper data dir
  file: path=/var/lib/zookeeper/data state=directory owner=zookeeper group=zookeeper mode=0770

- name: Create ZooKeeper datalog dir
  file: path=/var/lib/zookeeper/datalog state=directory owner=zookeeper group=zookeeper mode=0770

- name: Create ZooKeeper transactions dir
  file: path=/var/lib/zookeeper/transactions state=directory owner=zookeeper group=zookeeper mode=0770

- name: Create ZooKeeper logs dir
  file: path=/var/log/zookeeper state=directory owner=zookeeper group=zookeeper mode=0770

- name: Template zoo.cfg
  template: src=zoo.j2 dest=/opt/zookeeper/conf/zoo.cfg owner=zookeeper group=zookeeper mode=0660

- name: Copy log4j.properties
  copy: src=log4j.properties dest=/opt/zookeeper/conf/log4j.properties owner=zookeeper group=zookeeper mode=0664

- name: Set myid
  shell: "echo {{ zookeeper_id }} > /var/lib/zookeeper/data/myid"

- name: Fix file permissions
  shell: chown -R zookeeper:zookeeper {{ item }}
  changed_when: false
  with_items:
  - /opt/zookeeper
  - /opt/{{ zookeeper_name }}
  - /var/lib/zookeeper
