---
- name: ZooKeeper base installation
  hosts: zookeeper
  user: "{{ install_user }}"
  become: yes
  gather_facts: no
  environment: "{{ proxy_env }}"

  pre_tasks:
    - name: 'Install Python'
      raw: 'sudo apt -y install python'

  roles:
    - zookeeper

- name: Exhibitor installation
  hosts: zookeeper
  user: "{{ install_user }}"
  become: yes
  gather_facts: no
  environment: "{{ proxy_env }}"
  roles:
    - exhibitor
