---

- name: Download Kafka Manager version {{ kafka_manager_version }} sources
  get_url: "url={{ kafka_manager_url }} dest=/tmp/{{ kafka_manager_file }}"

- name: Extract Kafka Manager sources
  unarchive: "src=/tmp/{{ kafka_manager_file }} dest=/tmp owner=zookeeper group=zookeeper remote_src=yes"

- name: Build Kafka Manager
  shell: ./sbt clean dist
  args:
    chdir: "/tmp/{{ kafka_manager_name }}"

- name: Install unzip
  apt:
    pkg:
      - unzip
    state: latest

- name: Unzip Kafka Manager to /opt
  unarchive: "src=/tmp/{{ kafka_manager_name }}/target/universal/{{ kafka_manager_name }}.zip dest=/opt owner=zookeeper group=zookeeper remote_src=yes"

- name: Create Kafka Manager "kafkamanager" symlink
  file: "src=/opt/{{ kafka_manager_name }} dest=/opt/kafka-manager owner=zookeeper group=zookeeper state=link"

- name: Template Zookeeper servers spec
  template: src=zookeeper_servers_spec.j2 dest=/tmp/zookeeper_servers_spec mode=0664

- name: Load Zookeeper servers spec
  shell: cat /tmp/zookeeper_servers_spec
  register: zookeeper_servers_spec

- name: Set zookeeper_servers_spec fact
  set_fact: zookeeper_servers_spec={{ zookeeper_servers_spec.stdout }}

- name: Show zookeeper_servers_spec
  debug: var=zookeeper_servers_spec

- name: Replace Zookeeper hosts to Kafka Manager configuration file
  lineinfile:
    path: /opt/{{ kafka_manager_name }}/conf/application.conf
    regexp: '^kafka-manager.zkhosts=.*}'
    line: 'kafka-manager.zkhosts="{{ zookeeper_servers_spec }}"'
    owner: zookeeper
    group: zookeeper
    mode: '0644'
    backup: yes

- name: Fix file permissions
  file:
    path: /opt/{{ kafka_manager_name }}
    state: directory
    recurse: yes
    owner: zookeeper
    group: zookeeper

- name: Copy Kafka Manager systemd service config
  copy: src=kafka_manager.service dest=/lib/systemd/system/kafka-manager.service owner=root group=root mode=0644 backup=yes

# Run Kafka Manager only on one zookeper host, default port 9000 (security group addition needed)
- name: Set Kafka Manager to autostart via systemd
  systemd:
    name: kafka-manager
    enabled: yes
    masked: no
  run_once: true

- name: Restart Kafka Manager
  systemd:
    name: kafka-manager
    state: restarted
  run_once: true
