---
- name: Create ZooKeeper Exhibitor dir
  file: path=/opt/exhibitor state=directory owner=zookeeper group=zookeeper mode=0770

- name: Create Exhibitor build dir
  file: path=/tmp/exhibitor state=directory mode=0777

- name: Download Exhibitor pom.xml file
  get_url: "url=https://raw.github.com/Netflix/exhibitor/master/exhibitor-standalone/src/main/resources/buildscripts/standalone/maven/pom.xml dest=/tmp/exhibitor/pom.xml"

- name: Install maven
  apt: name=maven state=present

- name: Build Exhibitor
  shell: mvn clean package
  args:
    chdir: "/tmp/exhibitor"

- name: Copy Exhibitor jar
  copy: "src=/tmp/exhibitor/target/{{ exhibitor_file }} dest=/opt/exhibitor/{{ exhibitor_file }} remote_src=yes mode=0550 force=no"

- name: Change Exhibitor permissions
  file: "path=/opt/exhibitor/{{ exhibitor_file }} owner=zookeeper group=zookeeper mode=0550"

- name: Create Exhibitor symlink
  file: "src=/opt/exhibitor/{{ exhibitor_file }} dest=/opt/exhibitor/exhibitor.jar state=link"

- name: Template servers spec
  template: src=servers_spec.j2 dest=/tmp/servers_spec mode=0664

- name: Load servers spec
  shell: cat /tmp/servers_spec
  register: servers_spec

- name: Set servers_spec fact
  set_fact: servers_spec={{ servers_spec.stdout }}

- name: Show servers_spec
  debug: var=servers_spec

- name: Copy ZooKeeper S3 credentials
  template: "src=zookeeper-s3-credentials.j2 dest=/opt/exhibitor/zookeeper-s3-credentials.properties owner=zookeeper group=zookeeper mode=0660"

- name: Template Exhibitor properties
  template: "src=exhibitor_properties.j2 dest=/opt/exhibitor/exhibitor.properties owner=zookeeper group=zookeeper mode=0660 backup=yes"

- name: Template exhibitor.sh
  template: src=exhibitor.j2 dest=/opt/exhibitor/exhibitor.sh owner=zookeeper group=zookeeper mode=0550 backup=yes

- name: Copy log4j.properties
  copy: src=log4j.properties dest=/opt/exhibitor/log4j.properties owner=zookeeper group=zookeeper mode=0660 backup=yes

- name: Update exhibitor.jar with log4j.properties
  shell: "jar uvf /opt/exhibitor/{{ exhibitor_file }} log4j.properties"
  args:
    chdir: /opt/exhibitor

- name: Copy Exhibitor systemd service config
  copy: src=exhibitor.service dest=/lib/systemd/system/exhibitor.service owner=root group=root mode=0644 backup=yes

- name: Fix file permissions
  file:
    path: /opt/exhibitor
    state: directory
    recurse: yes
    owner: zookeeper
    group: zookeeper

- name: Set Exhibitor to autostart via systemd
  systemd:
    name: exhibitor
    enabled: yes
    masked: no

- name: Restart Exhibitor
  systemd:
    name: exhibitor
    state: restarted
